-- Andy Bodell
use CPSC4620Project;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS orderdiscount;
DROP TABLE IF EXISTS pizzadiscount;
DROP TABLE IF EXISTS `order`;
DROP TABLE IF EXISTS dineinorder;
DROP TABLE IF EXISTS pickuporder;
DROP TABLE IF EXISTS deliveryorder;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS discount;
DROP TABLE IF EXISTS pizzatoppingrelationship;
DROP TABLE IF EXISTS topping;
DROP TABLE IF EXISTS pizza;
DROP TABLE IF EXISTS baseprice;
DROP SCHEMA IF EXISTS CPSC4620Project;
